<?php

if (!isset ($_GET["url"]) || empty ($_GET["url"]))
	die ("emtpy");


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/



if(substr( $_GET["url"], 0, 3 ) === "file"){

	$local = fopen($_GET["url"], "r");
	echo $local;
} else {

	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, $_GET["url"]);
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

	$headers = array();
	$headers[] = 'Accept: text/xml';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	echo $result;
}
?>
